export default interface IOffice {
    _id: string,
    name: string,
    location: string,
    description: string,
    price: number,
    size: number,
    types: Array<string>,
    position: {lat: number, lng: number},
    tags: Array<string>,
    images: Array<string>,
    documents: Array<string>,
    files: Array<string>,
    thumbnails: Array<string>,
    hidden: boolean,
}